name: Deploy Express App to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.AZURE_PORT }} ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Project to Azure VM
        run: |
          rsync -avz -e "ssh -p ${{ secrets.AZURE_PORT }}" ./onse-app/ ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }}:${{ secrets.APP_DIR }}

      - name: Install & Restart Server
        run: |
          ssh -p ${{ secrets.AZURE_PORT }} ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            cd ${{ secrets.APP_DIR }}/server
            npm install
            pm2 restart all || pm2 start index.js --name express-app
            pm2 save
          EOF
